name: Add multiple Docker images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_job:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./server --file Dockerfile --tag server:$(date +%s)

  push_job:
    needs: build_job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
        repository: ${{ secrets.DOCKER_HUB_USERNAME }}/server
        file: ./server/Dockerfile
        push: true
        tags: latest
     
